### ISSUE TITLE
Lisää Kaavatietomallin UKK

### ISSUE THREAD

**Issue by ilkkarinne** [sykefi/ry-tietomallit#38]
Lisätään Kaavatietomallin Usein Kysytyt Kysymykset -sivu vastauksineen, riippuu seikasta #37

**Comment by ilkkarinne** [comment]
Lisätty PDF-muotoisina tiedostoina ja linkit ylänavigaatioon toistaiseksi

**Comment by SannaJokela** [comment]
UKK-pdf on lisätty sivustolle. Laitan closatuksi.
